name 'BUSCO'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'apachev2'
description 'Installs/Configures BUSCO'
long_description 'Installs/Configures BUSCO'
source_url 'https://github.com/EagleGenomics-cookbooks/BUSCO'
issues_url 'https://github.com/EagleGenomics-cookbooks/BUSCO/issues'
version '0.1.0'
